spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      cache:
        period: 0

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cpt202.projectselection.domain
  configuration:
    map-underscore-to-camel-case: true
